# Generated by Django 4.0.4 on 2022-05-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlink_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница id, slug, namespace', 'verbose_name_plural': 'Страницы id, slug, namespace'},
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, verbose_name='Напишите контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='page',
            name='data_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата правки'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text='Максимум 160 символов', max_length=160, verbose_name='Напишите заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
