# Generated by Django 4.0.4 on 2022-06-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('personal_website', models.URLField(blank=True, default='Нет сайта')),
                ('picture', models.ImageField(default='nick.png', null=True, upload_to='info_notes_picture/')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Имя или ник автора',
                'verbose_name_plural': 'Имена или ники авторов',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 80 символов', max_length=80, unique=True, verbose_name='имя сайта')),
                ('website', models.URLField(blank=True, unique=True, verbose_name='Сайт')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('slug', models.SlugField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Название сайта',
                'verbose_name_plural': 'Название сайтов',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('content', models.TextField(max_length=2000)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('nick', models.ManyToManyField(to='info_notes1.nick')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_notes1.site')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
    ]
