# Generated by Django 4.0.4 on 2022-06-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_notes1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nick',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(max_length=80, null=True),
        ),
    ]
