# Generated by Django 4.0.4 on 2022-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_notes1', '0002_alter_nick_slug_alter_site_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nick',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
