# Generated by Django 4.0.4 on 2022-05-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=12, unique=True),
            preserve_default=False,
        ),
    ]
